# Generated by Django 5.2.17 on 2026-08-17 21:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Opaque durable identifier. Not an access-control mechanism.', primary_key=True, serialize=False)),
                ('manufacturer_part_number', models.TextField(blank=True, help_text='Canonical MPN from the request. May be empty if a description was supplied.')),
                ('description', models.TextField(blank=True, help_text='Canonical description from the request. May be empty if an MPN was supplied.')),
                ('state', models.CharField(choices=[('CREATED', 'CREATED'), ('RUNNING', 'RUNNING'), ('PARTIALLY_COMPLETED', 'PARTIALLY_COMPLETED'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='CREATED', editable=False, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('manufacturer_part_number__gt', ''), ('description__gt', ''), _connector='OR'), name='research_run_has_mpn_or_description'), models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', False), _connector='OR'), name='research_run_finished_implies_started')],
            },
        ),
    ]
