# Generated by Django 5.2.17 on 2026-08-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='researchrun',
            name='research_run_finished_implies_started',
        ),
        migrations.AddConstraint(
            model_name='researchrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('state', 'CREATED')), models.Q(('finished_at__isnull', True), ('started_at__isnull', False), ('state', 'RUNNING')), models.Q(('finished_at__isnull', False), ('started_at__isnull', False), ('state__in', ['COMPLETED', 'FAILED', 'PARTIALLY_COMPLETED'])), _connector='OR'), name='research_run_state_matches_timestamps'),
        ),
    ]
