# Generated by Django 5.2.17 on 2026-08-20 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_research_run_lifecycle_shape'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceIntelligenceSnapshot',
            fields=[
                ('run', models.OneToOneField(help_text='The research run this snapshot belongs to.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='price_intelligence_snapshot', serialize=False, to='runs.researchrun')),
                ('schema_version', models.PositiveSmallIntegerField(help_text='Codec version that produced the payload. Initial supported value is 1.')),
                ('payload', models.JSONField(help_text='Versioned codec-encoded PriceAggregationResult.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this snapshot record was persisted. Not source retrieval time or market-price freshness.')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='price_intelligence_snapshot_schema_version_gte_1')],
            },
        ),
    ]
