# Generated by Django 5.2.17 on 2026-08-21 23:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_add_price_intelligence_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='Ordered position of this attempt within the run. Must be unique per run and >= 1.')),
                ('stage', models.CharField(choices=[('SEARCH', 'SEARCH'), ('FETCH', 'FETCH'), ('EXTRACT', 'EXTRACT'), ('NORMALIZE', 'NORMALIZE'), ('MATCH', 'MATCH'), ('AGGREGATE', 'AGGREGATE')], help_text='The research primitive that was called.', max_length=16)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED'), ('BLOCKED', 'BLOCKED'), ('EMPTY', 'EMPTY')], help_text='The result of the primitive call.', max_length=16)),
                ('candidate_url', models.TextField(blank=True, help_text='The URL operated on, if applicable. Empty if not a URL-based primitive (e.g., SEARCH).')),
                ('detail_code', models.CharField(blank=True, help_text='Stable machine-readable code explaining the outcome. Never raw exception text.', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When this evidence record was persisted.')),
                ('run', models.ForeignKey(help_text='The research run this evidence belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='execution_evidence', to='runs.researchrun')),
            ],
            options={
                'ordering': ['run', 'attempt_number'],
                'indexes': [models.Index(fields=['run', 'attempt_number'], name='runs_execut_run_id_dc54d2_idx'), models.Index(fields=['run', 'stage'], name='runs_execut_run_id_b95a5d_idx'), models.Index(fields=['run', 'outcome'], name='runs_execut_run_id_637e42_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'attempt_number'), name='execution_evidence_unique_attempt_per_run'), models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='execution_evidence_attempt_number_ge_1'), models.CheckConstraint(condition=models.Q(('candidate_url', ''), ('candidate_url__regex', '^https?://'), _connector='OR'), name='execution_evidence_url_or_empty')],
            },
        ),
    ]
