# Generated by Django 5.2.17 on 2026-08-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_executionevidencerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionevidencerecord',
            name='stage',
            field=models.CharField(choices=[('SEARCH', 'SEARCH'), ('FETCH', 'FETCH'), ('EXTRACT', 'EXTRACT'), ('NORMALIZE', 'NORMALIZE'), ('MATCH', 'MATCH'), ('AGGREGATE', 'AGGREGATE'), ('SEMANTIC', 'SEMANTIC')], help_text='The research primitive that was called.', max_length=16),
        ),
    ]
