# Generated by Django 5.2.17 on 2026-09-30 21:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_research_micron_alias_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchfxsnapshot',
            name='acquisition',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('CACHE_HIT', 'CACHE_HIT')], default='LIVE', editable=False, help_text='How THIS run obtained its FX evidence: LIVE (provider fetch during this run) or CACHE_HIT (served from the canonical cross-run ECB observation store under the approved freshness contract). Display-provenance only; never changes the FX payload or its DISPLAY-SUPPLEMENTAL authority. REPLAY is a read behavior, never a stored value.', max_length=16),
        ),
        migrations.CreateModel(
            name='FxObservationStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Row identity (referential stability for re-proof updates).', primary_key=True, serialize=False)),
                ('feed_id', models.CharField(editable=False, help_text='Stable canonical feed identity (pre-fetch lookup key); the semantic external feed, not a provider class name.', max_length=64)),
                ('provider_id', models.CharField(editable=False, help_text="Feed invariant; must be 'ECB' for the canonical feed.", max_length=16)),
                ('base_currency', models.CharField(editable=False, help_text="Feed invariant; must be 'EUR' for the canonical feed.", max_length=3)),
                ('observation_date', models.DateField(editable=False, help_text="The document's own observation date (never 'today').")),
                ('content_sha256', models.CharField(editable=False, help_text='Canonical digest of the FULL parsed rate observation (research.fx_cache_contract.fx_document_content_sha256).', max_length=64)),
                ('payload', models.JSONField(editable=False, help_text='The FULL daily document encoded with the reused fail-closed FX codec V1 (research/fx_codec.py), including the original provider retrieved_at. The raw provider body is never persisted.')),
                ('original_retrieved_at', models.DateTimeField(editable=False, help_text='Original PROVIDER retrieval instant of the first live fetch of this exact content. IMMUTABLE; a re-proof never updates it and a cache hit serves it.')),
                ('last_proven_at', models.DateTimeField(editable=False, help_text='Timezone-aware instant of the last successful canonical live acquisition that proved the feed was serving this exact content (PROVEN_LATEST_AS_OF_T). An instant, never a date; updated only by the convergent conditional re-proof.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Row insertion instant.')),
            ],
            options={
                'indexes': [models.Index(fields=['feed_id', '-observation_date', '-last_proven_at'], name='fx_obs_latest_lookup')],
                'constraints': [models.UniqueConstraint(fields=('feed_id', 'observation_date', 'content_sha256'), name='fx_observation_store_unique_feed_date_content'), models.CheckConstraint(condition=models.Q(('feed_id__gt', '')), name='fx_observation_store_feed_id_not_empty'), models.CheckConstraint(condition=models.Q(('provider_id__gt', '')), name='fx_observation_store_provider_id_not_empty'), models.CheckConstraint(condition=models.Q(('base_currency__gt', '')), name='fx_observation_store_base_currency_not_empty'), models.CheckConstraint(condition=models.Q(('content_sha256__gt', '')), name='fx_observation_store_content_sha256_not_empty')],
            },
        ),
    ]
